spring.application.name=ApiGateway

server.port=9000
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG

# Keycloak configuration
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/Grade-Service/protocol/openid-connect/certs

# Routes
spring.cloud.gateway.routes[0].id=grade-service
spring.cloud.gateway.routes[0].uri=lb://GRADE-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/grades/**